### PR TITLE
Fabric 1.17 Port

### LINKED ISSUE #1: 1.17.1 Fabric Branch
Hi I have forked and created a 1.17.1 branch I'd like to PR which also involves a formatting clean up to match your forge layout, would you be able to create a `fabric_1.17` branch for the PR so it doesn't overwrite any existing branches?

### PR DESCRIPTION
**Pull request by AzureDoom**
This ports the mod to Fabric 1.17 fully along with a massive clean up to match the Forge version. Closes #1

### CODE REVIEW

**Comment by mactso** [comment]
Wow.  Thanks so much man!  
Hope this is useful to you on your server or in your modpack.

I'll use it as a guide to under stand 1.17 better.
I'll try to get out 1.18 immediately.   And now that me and lupicus are both healthy again, I'll try to keep a closer watch on git issues again.

**Comment by mactso** [comment]
I'll try and build this and test this by wednesday night and make it available for download.
MacTso

**Comment by AzureDoom** [comment]
Thanks! I updated it to the latest Loom as well so it should make 1.18 porting a lot easier for you!

**Comment by mactso** [comment]
Wonderful.  I'll try to get the 1.17 environment set up tomorrow.  Just finished resolving "fastforward" hell with another mod.

**Pull request merged**
